### ISSUE TITLE
Highlighting individual items

### ISSUE THREAD

**Issue by technicallyrice** [andreareina/cs419#3]
Right now we highlight an entire row of data, but we probably want to change this to highlight individual fields. This way, we can have it so we hit edit on an individual field and we can enter a new value for just that item and not have to edit the whole row. Unless we want to do it where we select a row to edit and we can edit any part of the row and save those changes.

**Comment by abbymeunier** [comment]
"self.mainScreen.edit_cell = 0"  automatically highlights the first value of the first row when the user switches tables.
